# Generated by Django 3.2.3 on 2021-05-26 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(default=18)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('GS', 'General_service'), ('NEU', 'Neurology'), ('ONC', 'Oncology'), ('PSY', 'Psychiatry'), ('PDT', 'Pediatrics'), ('DRT', 'Dermatology')], max_length=3, verbose_name='Department')),
                ('hospital', models.CharField(max_length=250, verbose_name='Hospital')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.agent', verbose_name='Agent')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.products', verbose_name='Product')),
            ],
        ),
    ]
