# Generated by Django 3.2.6 on 2021-09-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('leads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Api.leads')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
            bases=('Api.leads',),
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='leads',
            name='iscustomer',
            field=models.BooleanField(default=False, verbose_name='Customer'),
        ),
    ]
