# Generated by Django 3.2.6 on 2021-09-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210901_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='iscustomer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
