# Generated by Django 3.2.6 on 2021-09-02 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_products_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
